version: '3'

services:
    web:
        environment:
            ENV: testing
            # Add any other test-specific environment variable here, e.g.
            #SERVER_TIME: "2017-11-07 10:00:00"
